/*
 * Copyright (C) 2008, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: version.h.in,v 1.2 2008/04/23 16:19:15 Exp $
 *
*/

#ifndef _version_h_
#define _version_h_

#define	ROUTER_MAJOR_VERSION		5

#define	ROUTER_MINOR_VERSION		20

#define	ROUTER_RC_NUMBER		29

#define	ROUTER_INCREMENTAL_NUMBER	0

#define	ROUTER_BUILD_NUMBER		0

#define	ROUTER_VERSION			5, 20, 29, 0

#define	ROUTER_VERSION_NUM		0x05141d00

/* Version String, ASCII, 32 chars max */
#define	ROUTER_VERSION_STR		"5.20.29.0"

#endif /* _version_h_ */
