#define MAX_IPC_MSG_BUF 64

typedef struct
{
    long mtype;
    char mtext[MAX_IPC_MSG_BUF];
} msgbuf;

// linux IPC number need to greater than 1
enum {
	IPC_CLIENT_MSG_Q_ID = 1,
	IPC_START_AUTO_DET,
	IPC_LINK_STATE,
	IPC_ADD_PVC,
	//IPC_DEL_PVC,
	IPC_DEL_ALL_PVC,
	IPC_STOP_AUTO_DET,
	IPC_ATE_ADSL_SHOW,
	IPC_ATE_SET_ADSL_MODE,
	IPC_ATE_ADSL_DISP_PVC,
	IPC_ATE_ADSL_QUIT_DRV,
	IPC_RELOAD_PVC,
	IPC_ATE_ADSL_RESTORE_DEFAULT /* Paul add 2012/8/7 */
	, IPC_ATE_ADSL_GET_BITS_PER_CARRIER //Ren
	, IPC_ATE_ADSL_GET_SNR //Ren
	, IPC_ATE_ADSL1_GET_SNR //Ren
	, IPC_ATE_ADSL2_PLUS_GET_SNR //Ren
	, IPC_RELOAD_DSL_SETTING
#ifdef RTCONFIG_DSL_TCLINUX
	, IPC_INIT_AUTO_DET
	, IPC_GET_AUTO_DET_RESULT
	, IPC_ATE_CMD
	, IPC_ATE_GET_DSL_PERF
	, IPC_ATE_LED
	, IPC_SHOW_SNR
	, IPC_SHOW_BPC
#ifdef RTCONFIG_VDSL
	, IPC_ADD_PTM
#endif
#endif
};
