# $Id: Makefile,v 1.1.1.1 2007/08/03 18:51:51 Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
